### ISSUE TITLE
Crash while adding button with "last value" without suscriptions

### ISSUE THREAD

**Issue by PhantomSage** [xDWart/mqtg-bot#1]
Just a small glitch, the bot crashes (division by 0):
Preconditions: Fresh bot, with no subscriptions
Activity:
Added a folder
Added a button of type "last value"
Gave it a name, and division by 0 and dies
"Workaround":
Add a subscription first

**Comment by xDWart** [comment]
Fixed by [de16b28](https://github.com/xDWart/mqtg-bot/commit/de16b28951bd967bca041c8fc24d797c43d5d6cb) commit.
Thanks for creating issue!
