### ISSUE TITLE
БД

### ISSUE THREAD

**Issue by utya** [xDWart/mqtg-bot#5]
Добрый день. 
спасибо за проект подскажите, чтобы запустить бот у себя мне нужно поднять БД postgres?

**Comment by xDWart** [comment]
Добрый день.
Postgres не обязателен, по умолчанию будет использоваться SQLite. См. README

Notes:
1. Only TELEGRAM_BOT_TOKEN env is required
2. If DATABASE_URL env is omitted, or a Postgres connection error occurred, SQLite will be used
3. If SQLITE_PATH env is omitted, mqtg.db will be used by default as a SQLite database

**Comment by utya** [comment]
Спс
